INSERT INTO admins (name, email, password_hash, role, active)
SELECT 'Admin Demo', 'admin@rifagrid.local', '$2y$10$Mf9xA6nWx/QYMIS/ynlMIer8/CNYjbiqdbpmwDS2mePEUJ7kMh6RK', 'owner', 1
FROM (SELECT 1) AS seed
WHERE NOT EXISTS (
  SELECT 1 FROM admins WHERE email = 'admin@rifagrid.local'
);

SET @admin_id := (
  SELECT id FROM admins WHERE email = 'admin@rifagrid.local' ORDER BY id LIMIT 1
);

INSERT INTO raffles
(title, slug, description, first_prize, second_prize, third_prize, price_per_number, draw_date, status, theme, primary_color, accent_color, background_color, grid_style, yappy_number, contact_whatsapp, bank_info, item_cost, created_by)
SELECT
  'Mega Rifa Gourmand',
  'mega-rifa-gourmand',
  'Rifa demo para probar la grilla, reservas y flujo manual de pago.',
  'Cena premium gourmand',
  'Canasta especial',
  'Botella de cortesía',
  2.00,
  DATE_ADD(NOW(), INTERVAL 30 DAY),
  'active',
  'clean_sky',
  '#38aeea',
  '#f06292',
  '#eaf8ff',
  'soft_cards',
  '6000-0000',
  '50760000000',
  'Banco demo | Cuenta 000000 | GIBEL Rifas',
  80.00,
  @admin_id
FROM (SELECT 1) AS seed
WHERE NOT EXISTS (
  SELECT 1 FROM raffles WHERE slug = 'mega-rifa-gourmand'
);

SET @raffle_id := (
  SELECT id FROM raffles WHERE slug = 'mega-rifa-gourmand' ORDER BY id LIMIT 1
);

INSERT IGNORE INTO raffle_numbers (raffle_id, number_value, display_number)
SELECT @raffle_id, n, CASE WHEN n < 100 THEN LPAD(n, 2, '0') ELSE CAST(n AS CHAR) END
FROM (
  SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
  UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
  UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29
  UNION ALL SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39
  UNION ALL SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49
  UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59
  UNION ALL SELECT 60 UNION ALL SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL SELECT 64 UNION ALL SELECT 65 UNION ALL SELECT 66 UNION ALL SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69
  UNION ALL SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL SELECT 73 UNION ALL SELECT 74 UNION ALL SELECT 75 UNION ALL SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL SELECT 79
  UNION ALL SELECT 80 UNION ALL SELECT 81 UNION ALL SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84 UNION ALL SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL SELECT 88 UNION ALL SELECT 89
  UNION ALL SELECT 90 UNION ALL SELECT 91 UNION ALL SELECT 92 UNION ALL SELECT 93 UNION ALL SELECT 94 UNION ALL SELECT 95 UNION ALL SELECT 96 UNION ALL SELECT 97 UNION ALL SELECT 98 UNION ALL SELECT 99 UNION ALL SELECT 100
) numbers
WHERE @raffle_id IS NOT NULL;

INSERT INTO settings (setting_key, setting_value)
SELECT 'whatsapp_provider', 'manual_wa_me'
FROM (SELECT 1) AS seed
WHERE NOT EXISTS (SELECT 1 FROM settings WHERE setting_key = 'whatsapp_provider');

INSERT INTO settings (setting_key, setting_value)
SELECT 'lnb_official_url', 'https://www.lnb.gob.pa/'
FROM (SELECT 1) AS seed
WHERE NOT EXISTS (SELECT 1 FROM settings WHERE setting_key = 'lnb_official_url');

INSERT INTO whatsapp_configs (provider, phone_number, active)
SELECT 'manual', '50760000000', 0
FROM (SELECT 1) AS seed
WHERE NOT EXISTS (SELECT 1 FROM whatsapp_configs);
